# PYTORCH가 무엇인가요?
출처: [PyTorch Tutorials - PYTORCH가 무엇인가요?](https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

- NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우

- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

## 시작하기

### Tensors
Tensor는 NumPy의 ndarray와 유사하며, GPU를 사용한 연산 가속도 가능합니다.

In [1]:
from __future__ import print_function
import torch

In [2]:
# 초기화되지 않은 5x3 행렬을 생성합니다
x = torch.empty(5, 3)
print(x)

tensor([[-4.6215e+01,  3.0935e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0935e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -1.3610e+01]])


In [3]:
# 무작위로 초기화된 행렬을 생성합니다
x = torch.rand(5, 3)
print(x)

tensor([[0.2977, 0.8490, 0.6999],
        [0.7949, 0.2051, 0.8230],
        [0.2503, 0.6897, 0.8825],
        [0.0414, 0.4718, 0.2303],
        [0.0597, 0.0394, 0.9942]])


In [4]:
# dtype이 long이고 0으로 채워진 행렬을 생성합니다
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 데이터로부터 tensor를 직접 생성합니다
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 또는 기존 tensor를 바탕으로 새로운 tensor를 만듭니다.
# 이들 메소드(method)는 사용자로부터 새로운 값을 제공받지 않은 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 메소드는 크기를 받습니다
print(x)

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1202,  1.9721, -0.1347],
        [-0.2297, -0.8435,  1.2156],
        [ 0.7356, -0.2108,  0.3410],
        [ 0.5929, -1.6890,  0.0248],
        [ 0.4498,  0.5766,  1.7030]])


In [7]:
# 행렬의 크기를 구합니다
print(x.size())

torch.Size([5, 3])


## 연산(Operations)

연산을 위한 여러가지 문법을 제공합니다. 다음 예제들을 통해 덧셈 연산을 살펴보겠습니다.

In [8]:
# 덧셈: 문법1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4433,  2.9386,  0.1894],
        [ 0.2282,  0.1282,  1.9606],
        [ 1.5166,  0.1145,  0.4646],
        [ 1.0172, -1.4269,  0.8567],
        [ 1.0319,  1.2885,  1.7608]])


In [9]:
# 덧셈: 문법2
print(torch.add(x, y))

tensor([[ 0.4433,  2.9386,  0.1894],
        [ 0.2282,  0.1282,  1.9606],
        [ 1.5166,  0.1145,  0.4646],
        [ 1.0172, -1.4269,  0.8567],
        [ 1.0319,  1.2885,  1.7608]])


In [10]:
# 덧셈: 결과 tensor를 인자로 제공
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4433,  2.9386,  0.1894],
        [ 0.2282,  0.1282,  1.9606],
        [ 1.5166,  0.1145,  0.4646],
        [ 1.0172, -1.4269,  0.8567],
        [ 1.0319,  1.2885,  1.7608]])


In [11]:
# 덧셈: 바꿔치기(in-place) 방식

# y에 x 더하기
y.add_(x)
print(y)

tensor([[ 0.4433,  2.9386,  0.1894],
        [ 0.2282,  0.1282,  1.9606],
        [ 1.5166,  0.1145,  0.4646],
        [ 1.0172, -1.4269,  0.8567],
        [ 1.0319,  1.2885,  1.7608]])


In [12]:
# NumPy스러운 인덱싱 표기 방법을 사용하실 수도 있습니다!
print(x[:, 1])

tensor([ 1.9721, -0.8435, -0.2108, -1.6890,  0.5766])


In [13]:
# 크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원에서 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# 만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2254])
0.2254418581724167


#### 더 읽을거리

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등, 100가지 이상의 Tensor 연산은 [여기](https://pytorch.org/docs/stable/torch.html) 에서 확인하실 수 있습니다.

## NumPy 변환(Bridge)
Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

### Torch Tensor를 NumPy 배열로 변환하기

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
# NumPy 배열의 값이 어떻게 변하는지 확인해보세요.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## NumPy 배열을 Torch Tensor로 변환하기
np (NumPy) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로 변환할 수 있고, (NumPy에서 Tensor로의) 반대 변환도 가능합니다.

## CUDA Tensors
.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.

In [19]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

# Out:
# tensor([1.8994], device='cuda:0')
# tensor([1.8994], dtype=torch.float64)